<?php

namespace AppBundle\Repository;

/**
 * CodeCheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeCheckRepository extends \Doctrine\ORM\EntityRepository
{
}
