<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $userId
     * @return array
     */
    public function findProjectsByUserId($userId)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.users', 'u')
            ->where('u.id = :user_id')
            ->setParameter('user_id', $userId)
            ->getQuery()->getResult();
    }
}
